# -*- mode: ruby -*-
# vi: set ft=ruby :
####
#
# This is the template that was generated by capifony
#
# @see https://github.com/everzet/capifony/blob/master/bin/capifony
#
load 'deploy' if respond_to?(:namespace) # cap2 differentiator

require 'capifony_symfony2'
load '#{symfony_app_path}/config/deploy'

# Load in the multistage configuration and setup the stages
set :stages,        %w(beta production)
set :default_stage, "beta"
set :stage_dir,     "app/config"
# @see https://github.com/capistrano/capistrano/wiki/2.x-Multistage-Extension
require 'capistrano/ext/multistage'

# If web/uploads will not be used, remove it
set :shared_children,    %w(web/uploads app/logs)
set :shared_files,       %w()
