imports:
    - { resource: config.yml }

#
# Framework configuration
# @see http://symfony.com/doc/master/reference/configuration/framework.html
#
framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    ide:      %framework_ide%

#
# Profiler Configuration
# @see http://symfony.com/doc/master/reference/configuration/web_profiler.html
#
web_profiler:
    toolbar:             %enable_profiler%
    intercept_redirects: false

#
# Monolog Configuration
# @see http://symfony.com/doc/master/reference/configuration/monolog.html
#
monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
#        firephp:
#            type:  firephp
#            level: info
        chromephp:
            type:  chromephp
            level: info

#
# Assetic Configuration
# @see http://symfony.com/doc/master/reference/configuration/assetic.html
#
assetic:
    use_controller: true

#
# Swiftmailer Configuration
# @see http://symfony.com/doc/master/reference/configuration/swiftmailer.html
#
swiftmailer:
    delivery_address: %developer_email%
