####
#
# Production Server Configuration
#
parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     '3306'
    database_name:     symfony
    database_user:     root
    database_password: root
    mailer_transport:  sendmail
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~
    locale:            en
    secret:            3e43fc1e52678f4ba74ec10e56450b86
